---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: observer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: observer
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: datastore
  labels:
    app: datastore
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: datastore