---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
        - name: mongodb
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017