---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: agent
  labels:
    app: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: localhost:5000/agent
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: travelagent-data
                  key: agenturl
            - name: AIRLINE_SERVICE_URL
              value: "http://airline"
            - name: AUTO_SERVICE_URL
              value: "http://auto"
            - name: HOTEL_SERVICE_URL
              value: "http://hotel"
            - name: USER_SERVICE_URL
              value: "http://users"
      initContainers:
        - name: init-myservice
          image: busybox:1.31
          command: ['sh', '-c', 'until nslookup agent; do echo waiting for agent; sleep 2; done;']