apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: pinger
      image: reselbob/pinger
      env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: travelagent-data
              value: agenturl
  restartPolicy: Never